# Generated by Django 3.2.5 on 2023-08-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_account_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="entry_no",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
