# Generated by Django 3.2.5 on 2023-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0005_alter_transaction_entry_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="from_currency",
            field=models.CharField(
                choices=[
                    ("MZN", "MZN"),
                    ("USD", "USD"),
                    ("ZAR", "ZAR"),
                    ("AED", "AED"),
                    ("EUR", "EUR"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_currency",
            field=models.CharField(
                choices=[
                    ("MZN", "MZN"),
                    ("USD", "USD"),
                    ("ZAR", "ZAR"),
                    ("AED", "AED"),
                    ("EUR", "EUR"),
                ],
                max_length=3,
            ),
        ),
    ]
