# Generated by Django 3.2.5 on 2023-09-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20230819_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': [('view_yourmodel', 'Can view YourModel'), ('edit_yourmodel', 'Can edit YourModel')]},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='divide_by',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='multiply_by',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='narration',
            field=models.TextField(default='no narration', max_length=200),
            preserve_default=False,
        ),
    ]
