# Generated by Django 3.2.5 on 2023-09-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name',
        ),
    ]
