# Generated by Django 3.2.5 on 2023-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20230910_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='short',
            field=models.CharField(help_text='Turn On Capslock', max_length=3),
        ),
    ]
