# Generated by Django 3.2.6 on 2023-09-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_currency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_openings', to='transactions.account')),
            ],
        ),
    ]
