# Generated by Django 3.2.6 on 2023-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_currencyopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyopening',
            name='opening',
            field=models.FloatField(default=0.0, max_length=4),
        ),
    ]
