# Generated by Django 3.2.6 on 2023-10-06 12:49

import apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_currencyopening_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyopening',
            name='opening',
            field=models.FloatField(validators=[apps.transactions.models.validate_decimals]),
        ),
    ]
