# Generated by Django 3.2.6 on 2023-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_currencyopening_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='entry_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
