# Generated by Django 3.2.6 on 2023-11-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_alter_transaction_entry_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pre_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='pre_time',
        ),
    ]
