# Generated by Django 3.2.6 on 2023-11-05 12:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20231101_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile_1',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+923402111777', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile_2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='note',
            field=models.TextField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
