# Generated by Django 3.2.6 on 2023-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_alter_account_mobile_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
