# Generated by Django 3.2.6 on 2023-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20231107_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_archived',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
