# Generated by Django 3.2.6 on 2023-12-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='authorize',
            field=models.BooleanField(default=True),
        ),
    ]
